version: 2
jobs:
  build:
    docker:
      - image: golang:1.8

    working_directory: /go/src/github.com/mundipagg/boleto-api
    steps:
      - checkout

      - run:
          name: Get dependencies
          command: go get -t -d -v ./...
      - run: 
          name: Building
          command: go build -v
      - run: 
          name: Testing
          command: go test $(go list ./... | grep -v /vendor/) -v   
