version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    
    working_directory: /go/src/github.com/mundipagg/boleto-api

    steps:
      - checkout

      - run:
          name: Get dependencies
          command: go get -t -d -v ./...
      - run: 
          name: Building
          command: go build -v
      - run: 
          name: Testing
          command: go test $(go list ./... | grep -v /vendor/) -v   
  deploy:
    working_directory: /go/src/github.com/mundipagg/boleto-api/devops
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          PROJECT_NAME: one/boleto-api
    steps:
      - setup_remote_docker
      - deploy:
          name: Push application Docker image
          command: |
            ls -la
            docker build -t ${DOCKER_ACCOUNT}/${PROJECT_NAME} .
            docker login ${DOCKER_ACCOUNT} -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag ${DOCKER_ACCOUNT}/${PROJECT_NAME} "${DOCKER_ACCOUNT}/${PROJECT_NAME}:${CIRCLE_BRANCH}"
            docker tag ${DOCKER_ACCOUNT}/${PROJECT_NAME} "${DOCKER_ACCOUNT}/${PROJECT_NAME}:${CIRCLE_SHA1:0:8}"
            docker push "${DOCKER_ACCOUNT}/${PROJECT_NAME}"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          